version: 0.2
env:
  variables:
    JAVA_HOME: "/usr/lib/jvm/java-8-openjdk-amd64"
phases:
  install:
    commands:
      - echo installing maven...
      - apt-get update -y
      - apt-get install -y maven
  build:
    commands:
      - cd backend
      - echo entered building-phase
      - mvn clean install
artifacts:
  files:
    - backend/target/backend-1.0-aws.jar
    - backend/appspec.yml
  discard-paths: yes
cache:
  paths:
    - '/root/.m2/**/*'
