version: 0.2

env:
  variables:
    CACHE_CONTROL: "86400"
    S3_BUCKET: "{{http://www.bffl.com.s3-website.eu-central-1.amazonaws.com}}"
    BUILD_FOLDER: "dist"
phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - cd frontend
      - echo Installing source NPM dependencies...
      - npm install
      - npm install -g @angular/cli
  build:
    commands:
      - echo Build started
      - ng build --prod
artifacts:
  files:
    - '**/*'
  base-directory: 'frontend/dist*'
  discard-paths: yes
