version: 0.1
  environment_variables:
    plaintext:
      JAVA_HOME: "/opt/java-8-openjdk-amd64"
  phases:
    install:
      commands:
        - apt-get update -y
        - apt-get install -y maven
    build:
      commands:
        - cd backend
        - echo Starting build `date`
        - mvn clean package
    post_build:
      commands:
        - echo Build completed on `date`
  artifacts:
    files:
      - target/bffl-backend.jar
  discard-paths: yes
