version: 0.1

phases:
  install:
    commands:
      - curl -sL https://deb.nodesource.com/setup_12.x | bash -
      - apt-get install -y nodejs
      - curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
      - apt install --no-install-recommends yarn
  pre_build:
    commands:
      - npm i -g @angular/cli
      - npm install
  build:
    commands:
      - ng build --prod
artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: dist/bffl
