version: 0.2

env:
  variables:
    BUILD_NUMBER:

phases:
  install:
    commands:
      - yum update -y
  pre_build:
    commands:
      - echo starting pre-build `date`
      - java -version
      - mvn -version
  build:
    commands:
      - cd backend
      - echo Starting build `date`
      - mvn clean install
  post_build:
    commands:
      - echo Build completed on `date`
  test:
    commands:
      - echo Starting test `date`
      - mvn test
artifacts:
  files:
    - /backend/target/bffl-backend-1.0-exec.jar
discard-paths: yes
