version: 0.2

env:
  variables:
    BUILD_NUMBER:

phases:
  install:
    commands:
      - yum update -y
      - cd backend
  pre_build:
    commands:
      - echo Starting test on `date`
      - mvn test
      - echo Finished test on `date`
  build:
    commands:
      - echo Starting build on `date`
      - mvn clean install
      - echo Finished build on `date`
  post_build:
    commands:
      - mv target/bffl-backend-1.0.jar /
artifacts:
  files:
    - bffl-backend-1.0.jar
