version: 0.2

phases:
  install:
    commands:
      - yum update -y
      - yum install -y maven
  build:
    commands:
      - echo Starting build `date`
      - mvn clean install
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - target/bffl-backend.jar
discard-paths: yes
